server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    appname: feign-server
    metadata-map:
      cluster: moredo

ribbon:
  eureka:
    enabled: true

security:
  sessions: NEVER


spring:
  zipkin:
    base-url: 'http://zipkin:7411/'
    enabled: false